# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UICollectionViewExtandCell' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UICollectionViewExtandCell
  pod 'SnapKit'
  pod 'Then'

  target 'UICollectionViewExtandCellTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UICollectionViewExtandCellUITests' do
    # Pods for testing
  end

end
