# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UICollectionView_Extandable' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UICollectionView_Extandable
  pod 'SnapKit'
  pod 'Then'

  target 'UICollectionView_ExtandableTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UICollectionView_ExtandableUITests' do
    # Pods for testing
  end

end
